### ISSUE TITLE
Directing program towards folder rather than download by CIK

### ISSUE THREAD

**Issue by MartinLe5** [bws0013/read_13f#10]
Unfortunately I don't program in java (I'm at best an intermediate R user), but could this program be modified to point towards a folder that has 13F fillings (Such as your "examples" folder) rather than having to download x amount of fillings?  

Cheers,
Martin

**Comment by bws0013** [comment]
I have this in version 2 that will be released at some point. But that would definitely be a useful addition to this version. I'm just spitballing here so feel free to provide an opposing view but I would probably allow a user to point to a folder say HOME/ and within that folder they could have subfolders with the names of the ciks, so like HOME/123123123 and HOME/123456789. Then as a user you would just enter in the cik numbers and it would look inside those folders. And thinking about it some more you wouldn't even need to have those folder names be the ciks. 

Yeah this is actually a really good idea. I will look to add it. Thank you for the suggestion.

**Comment by MartinLe5** [comment]
I was just thinking a loose folder (for example, by are sorted by quarter).  Or does that create another problem since you use the entered CIK as the ID for the output?  

Also, I was thinking that this has the benefit of manual intervention if a file chokes the program (Like those annoying 2 lines per filing format) , it can be moved to a "problem files folder" for manual parsing and then restarted after the offending files are removed.  

Thanks,

**Comment by bws0013** [comment]
I will be on a business trip for the next week but will take a look at this and probably code something up next weekend.

**Comment by MartinLe5** [comment]
Thanks, super appreciated.  This is literally what I was looking for to work on a chapter of my thesis.

**Comment by bws0013** [comment]
I have finished the code on another branch and will be updating the documentation later and moving it to master. Everything should be fully ready to use in the next 12 hours.

**Comment by bws0013** [comment]
You now have the ability to read local copies. I am still fixing option 5 to know if files won't work. Now you can just drag folders of ciks into the examples/local_filings folder. It also includes this info in the instructions. 

If you end up using this for any kind of public paper I would love to take a look. I'm just curious to see how this could be used by other people.

**Comment by MartinLe5** [comment]
1) Really appreciate this.  One thing I really love about R is that packages have a preferred citation function.  Do you have one for this?.

2) I tried to get this to work via powershell on my windows machine (I'll give my Linux machine a try tomorrow).  I don't know if the problem is between my chair and my keyboard, but I'm not able to get the local stuff to work.

Here's the log

##Using the a folder named after the CIK

PS C:\Users\marti> cd C:\read_13f-master\Just_Do_It_Already
PS C:\read_13f-master\Just_Do_It_Already> java -jar Get_13f.jar

Enter the (n)umber from the options listed (ie c in this case)
(1) Read data into a sqlite3 database
(2) Read data into a csv file
(3) Read local data into a sqlite3 database
(4) Read local data into a csv file
(5) Read a directory for files that cannot be parsed
(q)uit
>4
Remember to enter the file extension of your .db or .csv file.
Enter the name of the csv you would like to use
>test.csv
Now you can enter CIK numbers one at a time
When you are finished entering ciks press # then press enter.
Enter a CIK or # then press enter
>0000002110
Enter a CIK or # then press enter
>#
What is the maximum number of quarterly filings you would like to retrieve
(Enter either: 10, 20, 40, 80 or 100)
>10
Obtaining Documents for: 0000002110
Exception in thread "main" java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Unknown Source)
        at java.util.Arrays$ArrayList.<init>(Unknown Source)
        at java.util.Arrays.asList(Unknown Source)
        at com.ben.smith.reader.Local_Reads.extract_files_from_folder(Local_Reads.java:18)
        at com.ben.smith.reader.Main.pass_data_local(Main.java:177)
        at com.ben.smith.reader.Main.menu(Main.java:93)
        at com.ben.smith.reader.Main.main(Main.java:27)
PS C:\read_13f-master\Just_Do_It_Already>


##using the entire path of the folder named after the CIK

PS C:\read_13f-master\Just_Do_It_Already> java -jar Get_13f.jar

Enter the (n)umber from the options listed (ie c in this case)
(1) Read data into a sqlite3 database
(2) Read data into a csv file
(3) Read local data into a sqlite3 database
(4) Read local data into a csv file
(5) Read a directory for files that cannot be parsed
(q)uit
>4
Remember to enter the file extension of your .db or .csv file.
Enter the name of the csv you would like to use
>test.csv
Now you can enter CIK numbers one at a time
When you are finished entering ciks press # then press enter.
Enter a CIK or # then press enter
>C:\read_13f-master\examples\local_filings\0000002110
Enter a CIK or # then press enter
>#
What is the maximum number of quarterly filings you would like to retrieve
(Enter either: 10, 20, 40, 80 or 100)
>10
Obtaining Documents for: C:\read_13f-master\examples\local_filings\0000002110
Exception in thread "main" java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Unknown Source)
        at java.util.Arrays$ArrayList.<init>(Unknown Source)
        at java.util.Arrays.asList(Unknown Source)
        at com.ben.smith.reader.Local_Reads.extract_files_from_folder(Local_Reads.java:18)
        at com.ben.smith.reader.Main.pass_data_local(Main.java:177)
        at com.ben.smith.reader.Main.menu(Main.java:93)
        at com.ben.smith.reader.Main.main(Main.java:27)
PS C:\read_13f-master\Just_Do_It_Already>

##Using the a folder named after the a quarter (Containing 2530 filings)

PS C:\read_13f-master\Just_Do_It_Already> java -jar Get_13f.jar

Enter the (n)umber from the options listed (ie c in this case)
(1) Read data into a sqlite3 database
(2) Read data into a csv file
(3) Read local data into a sqlite3 database
(4) Read local data into a csv file
(5) Read a directory for files that cannot be parsed
(q)uit
>4
Remember to enter the file extension of your .db or .csv file.
Enter the name of the csv you would like to use
>Test.csv
Now you can enter CIK numbers one at a time
When you are finished entering ciks press # then press enter.
Enter a CIK or # then press enter
>2000Q4
Enter a CIK or # then press enter
>#
What is the maximum number of quarterly filings you would like to retrieve
(Enter either: 10, 20, 40, 80 or 100)
>100
Obtaining Documents for: 2000Q4
Exception in thread "main" java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Unknown Source)
        at java.util.Arrays$ArrayList.<init>(Unknown Source)
        at java.util.Arrays.asList(Unknown Source)
        at com.ben.smith.reader.Local_Reads.extract_files_from_folder(Local_Reads.java:18)
        at com.ben.smith.reader.Main.pass_data_local(Main.java:177)
        at com.ben.smith.reader.Main.menu(Main.java:93)
        at com.ben.smith.reader.Main.main(Main.java:27)
PS C:\read_13f-master\Just_Do_It_Already>

**Comment by bws0013** [comment]
I'm looking into this, I think I see the problem and will code up the solution in a little while.

**Comment by MartinLe5** [comment]
OK, thanks

**Comment by bws0013** [comment]
Ok, its fixed. Everything should work, I actually tested it this time lol. If not please let me know.
