### ISSUE TITLE
Possible to pull a list of CIKs all at once without manual input?

### ISSUE THREAD

**Issue by hohoCode** [bws0013/read_13f#14]
First of all, thanks for the opensource. Great tool.

Currently it requires users to input CIK manually one at a time. Wondering if this is possible for the tool to pull a list of CIKs all at once? For example, the tool can take in a txt file which has a list of CIKs, and generate one or more CSV files as the output.

Thanks.

**Comment by bws0013** [comment]
Somehow didn't notice this until now. It's possible to input a list of CIKs, but this would require some re-engineering of the UI. I'm not really working on this anymore, but anyone else is welcome to make these changes.
